//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvertisementApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AdvertisementDBEntities : DbContext
    {
        public AdvertisementDBEntities()
            : base("name=AdvertisementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advert> Adverts { get; set; }
        public virtual DbSet<Category> Categorys { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<GetAllAdverts_Result> GetAllAdverts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllAdverts_Result>("GetAllAdverts");
        }
    
        public virtual ObjectResult<GetSortedByCatAdverts_Result> GetSortedByCatAdverts(string categoryId)
        {
            var categoryIdParameter = categoryId != null ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSortedByCatAdverts_Result>("GetSortedByCatAdverts", categoryIdParameter);
        }
    
        public virtual int NewAdvert(string title, string description, Nullable<decimal> price, Nullable<System.DateTime> date, Nullable<int> userId, Nullable<int> categoryId)
        {
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NewAdvert", titleParameter, descriptionParameter, priceParameter, dateParameter, userIdParameter, categoryIdParameter);
        }
    
        public virtual int NewUser(string userName, string password, string email, string address, string phoneNR)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var phoneNRParameter = phoneNR != null ?
                new ObjectParameter("PhoneNR", phoneNR) :
                new ObjectParameter("PhoneNR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NewUser", userNameParameter, passwordParameter, emailParameter, addressParameter, phoneNRParameter);
        }
    
        public virtual ObjectResult<SearchAdvertOnTitle_Result> SearchAdvertOnTitle(string userInput)
        {
            var userInputParameter = userInput != null ?
                new ObjectParameter("UserInput", userInput) :
                new ObjectParameter("UserInput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAdvertOnTitle_Result>("SearchAdvertOnTitle", userInputParameter);
        }
    
        public virtual ObjectResult<GetUserAdverts_Result> GetUserAdverts(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserAdverts_Result>("GetUserAdverts", userIdParameter);
        }
    
        public virtual ObjectResult<SearchAdvertOnTitleAndCategory_Result> SearchAdvertOnTitleAndCategory(Nullable<int> categoryId, string userInput)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var userInputParameter = userInput != null ?
                new ObjectParameter("UserInput", userInput) :
                new ObjectParameter("UserInput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAdvertOnTitleAndCategory_Result>("SearchAdvertOnTitleAndCategory", categoryIdParameter, userInputParameter);
        }
    }
}
